### ISSUE TITLE
hope curl_to_requests , 😄

### ISSUE THREAD

**Issue by johnson7788** [ritajie/requests_to_curl#1]

**Comment by ritajie** [comment]
@johnson7788 Thanks for the interesting suggestion!

I have no plans to do it considering the current schedule. But I can introduce you to a convenient way to achieve this functionality: use a third-party tool - Postman.

1. Import cURL into Postman
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/26023242/200976990-71b70e06-4890-44df-9766-fb9347e815a4.png">

2. Generate Python code with Postman
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/26023242/200977105-8472b5d0-3f6e-4367-a6e6-64770594836d.png">
