### ISSUE TITLE
Remove forced printing

### ISSUE THREAD

**Issue by cemkavuklu** [ritajie/requests_to_curl#2]
https://github.com/ritajie/requests_to_curl/blob/c3f89134db77a3cfcf78257e85aa8eb44b560f9d/requests_to_curl/requests_to_curl.py#L45

Please consider removing forced printing since there may be sensitive information (e.g. access tokens, passwords, etc.) in the request or response.
Also `return_it=True` should be the default behavior to avoid boilerplate.

**Comment by ritajie** [comment]
Agreed!

Thanks for the suggestion, around this week I'll find time to finish this update🙌

**Comment by cemkavuklu** [comment]
Just FYI, I wanted to open up a PR but it was not possible to do so. You might want to look into that if you would like to get contributions.

Have a great day.

**Comment by ritajie** [comment]
@cemkavuklu The update is complete: [Version 1.1.0](https://pypi.org/project/requests-to-curl/1.1.0/) 🚀
